# smh

---

**Project**  
- <project-name>

**Module**  
- notebooks

**Author**  
- MIN

**Created**  
- 2026-03-06

**Purpose**  
- TODO: Describe this notebook

---

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./data/BankChurners.csv')
df

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.999910
1,818770008,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.999940
2,713982108,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.999980
3,769911858,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.999870
4,709106358,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.999980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [3]:
df = df.drop([
    'CLIENTNUM',
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1',
    'Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2'
], axis=1)
df.head()

,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,Total_Relationship_Count,Months_Inactive_12_mon,Contacts_Count_12_mon,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

In [4]:
rename_dict = {
    "Attrition_Flag":"churn",
    "Customer_Age":"age",
    "Gender":"gender",
    "Dependent_count":"dependents",
    "Education_Level":"education",
    "Marital_Status":"marital",
    "Income_Category":"income",
    "Card_Category":"card_type",
    "Months_on_book":"relationship_months",
    "Total_Relationship_Count":"product_count",
    "Months_Inactive_12_mon":"inactive_months",
    "Contacts_Count_12_mon":"contact_count",
    "Credit_Limit":"credit_limit",
    "Total_Revolving_Bal":"revolving_balance",
    "Avg_Open_To_Buy":"available_credit",
    "Total_Amt_Chng_Q4_Q1":"amount_change",
    "Total_Ct_Chng_Q4_Q1":"count_change",
    "Total_Trans_Amt":"transaction_amount",
    "Total_Trans_Ct":"transaction_count",
    "Avg_Utilization_Ratio":"utilization_ratio"
}

df = df.rename(columns=rename_dict)
df.head()

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000

In [5]:
gender_ser = df['gender'].copy()
gender_ser = gender_ser.map(lambda x: 0 if x == 'M' else 1)
# gender_ser

gender_df = pd.DataFrame({
    'gender':df['gender'],
    'gender_encoded':gender_ser
})
gender_df

      gender  gender_encoded
0          M               0
1          F               1
2          M               0
3          F               1
4          M               0
...      ...             ...
10122      M               0
10123      M               0
10124      F               1
10125      M               0
10126      F               1

[10127 rows x 2 columns]

In [6]:
"""
| income_id | income_label   | min    | max    |
| --------- | -------------- | ------ | ------ |
| 1         | Less than $40K | 0      | 40000  |
| 2         | $40K-$60K      | 40000  | 60000  |
| 3         | $60K-$80K      | 60000  | 80000  |
| 4         | $80K-$120K     | 80000  | 120000 |
| 5         | $120K+         | 120000 | NULL   |
| 6         | Unknown        | NULL   | NULL   |
"""

'\n| income_id | income_label   | min    | max    |\n| --------- | -------------- | ------ | ------ |\n| 1         | Less than $40K | 0      | 40000  |\n| 2         | $40K-$60K      | 40000  | 60000  |\n| 3         | $60K-$80K      | 60000  | 80000  |\n| 4         | $80K-$120K     | 80000  | 120000 |\n| 5         | $120K+         | 120000 | NULL   |\n| 6         | Unknown        | NULL   | NULL   |\n'

In [7]:
def income_match(x):
    match x:
        case "Less than $40K":
            return 1
        case "$40K - $60K":
            return 2
        case "$60K - $80K":
            return 3
        case "$80K - $120K":
            return 4
        case "$120K +":
            return 5
        case "Unknown":
            return 6

In [8]:
income_ser = df['income'].copy()
income_ser = income_ser.apply(income_match)

income_df = pd.DataFrame({
    'income':df['income'],
    'income_encoded':income_ser
})
income_df

               income  income_encoded
0         $60K - $80K               3
1      Less than $40K               1
2        $80K - $120K               4
3      Less than $40K               1
4         $60K - $80K               3
...               ...             ...
10122     $40K - $60K               2
10123     $40K - $60K               2
10124  Less than $40K               1
10125     $40K - $60K               2
10126  Less than $40K               1

[10127 rows x 2 columns]

In [ ]:
"""
| card_type_id | card_type_label |
| ------------ | --------------- |
| 1            | Blue            |
| 2            | Silver          |
| 3            | Gold            |
| 4            | Platinum        |
"""

In [13]:
def card_type_match(x):
    match x:
        case "Blue":
            return 1
        case "Silver":
            return 2
        case "Gold":
            return 3
        case "Platinum":
            return 4

In [14]:
card_ser = df['card_type'].copy()
card_ser = card_ser.apply(card_type_match)

card_df = pd.DataFrame({
    'card_type':df['card_type'],
    'card_type_encoded':card_ser
})
card_df

      card_type  card_type_encoded
0          Blue                  1
1          Blue                  1
2          Blue                  1
3          Blue                  1
4          Blue                  1
...         ...                ...
10122      Blue                  1
10123      Blue                  1
10124      Blue                  1
10125      Blue                  1
10126    Silver                  2

[10127 rows x 2 columns]

In [ ]:
"""
| marital_id | marital_label |
| ---------- | ------------- |
| 1          | Single        |
| 2          | Married       |
| 3          | Divorced      |
| 4          | Unknown       |
"""

In [17]:
def marital_match(x):
    match x:
        case "Single":
            return 1
        case "Married":
            return 2
        case "Divorced":
            return 3
        case "Unknown":
            return 4

In [18]:
marital_ser = df['marital'].copy()
marital_ser = marital_ser.apply(marital_match)

marital_df = pd.DataFrame({
    'marital':df['marital'],
    'marital_encoded':marital_ser
})
marital_df

        marital  marital_encoded
0       Married                2
1        Single                1
2       Married                2
3       Unknown                4
4       Married                2
...         ...              ...
10122    Single                1
10123  Divorced                3
10124   Married                2
10125   Unknown                4
10126   Married                2

[10127 rows x 2 columns]

In [ ]:
"""
| education_id | education_label |
| ------------ | --------------- |
| 1            | Uneducated      |
| 2            | High School     |
| 3            | College         |
| 4            | Graduate        |
| 5            | Post-Graduate   |
| 6            | Doctorate       |
| 7            | Unknown         |
"""

In [19]:
def education_match(x):
    match x:
        case "Uneducated":
            return 1
        case "High School":
            return 2
        case "College":
            return 3
        case "Graduate":
            return 4
        case "Post-Graduate":
            return 5
        case "Doctorate":
            return 6
        case "Unknown":
            return 7

In [20]:
education_ser = df['education'].copy()
education_ser = education_ser.apply(education_match)

education_df = pd.DataFrame({
    'education':df['education'],
    'education_encoded':education_ser
})
education_df

         education  education_encoded
0      High School                  2
1         Graduate                  4
2         Graduate                  4
3      High School                  2
4       Uneducated                  1
...            ...                ...
10122     Graduate                  4
10123      Unknown                  7
10124  High School                  2
10125     Graduate                  4
10126     Graduate                  4

[10127 rows x 2 columns]

In [21]:
churn_ser = df['churn'].copy()
churn_ser = churn_ser.map(lambda x: 1 if x == 'Existing Customer' else 0)
# churn_ser

churn_df = pd.DataFrame({
    'churn':df['churn'],
    'churn_encoded':churn_ser
})
churn_df

                   churn  churn_encoded
0      Existing Customer              1
1      Existing Customer              1
2      Existing Customer              1
3      Existing Customer              1
4      Existing Customer              1
...                  ...            ...
10122  Existing Customer              1
10123  Attrited Customer              0
10124  Attrited Customer              0
10125  Attrited Customer              0
10126  Attrited Customer              0

[10127 rows x 2 columns]

In [28]:
test_df = df.copy()
test_df

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,Existing Customer,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,Existing Customer,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,Existing Customer,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,Existing Customer,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,Existing Customer,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,Existing Customer,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,Attrited Customer,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,Attrited Customer,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,Attrited Customer,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,Attrited Customer,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [29]:
test_df['churn'] = test_df['churn'].map(lambda x: 1 if x == 'Existing Customer' else 0)
test_df

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,1,45,M,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,1,49,F,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,1,51,M,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,1,40,F,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,1,40,M,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,1,50,M,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,0,41,M,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,0,44,F,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,0,30,M,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,0,43,F,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [30]:
test_df['gender'] = test_df['gender'].map(lambda x: 0 if x == 'M' else 1)
test_df

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,1,45,0,3,High School,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,1,49,1,5,Graduate,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,1,51,0,3,Graduate,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,1,40,1,4,High School,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,1,40,0,3,Uneducated,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,1,50,0,2,Graduate,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,0,41,0,2,Unknown,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,0,44,1,1,High School,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,0,30,0,2,Graduate,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,0,43,1,2,Graduate,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [31]:
test_df['education'] = test_df['education'].apply(education_match)
test_df

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,1,45,0,3,2,Married,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,1,49,1,5,4,Single,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,1,51,0,3,4,Married,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,1,40,1,4,2,Unknown,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,1,40,0,3,1,Married,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,1,50,0,2,4,Single,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,0,41,0,2,7,Divorced,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,0,44,1,1,2,Married,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,0,30,0,2,4,Unknown,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,0,43,1,2,4,Married,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [32]:
test_df['marital'] = test_df['marital'].apply(marital_match)
test_df

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,1,45,0,3,2,2,$60K - $80K,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,1,49,1,5,4,1,Less than $40K,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,1,51,0,3,4,2,$80K - $120K,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,1,40,1,4,2,4,Less than $40K,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,1,40,0,3,1,2,$60K - $80K,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,1,50,0,2,4,1,$40K - $60K,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,0,41,0,2,7,3,$40K - $60K,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,0,44,1,1,2,2,Less than $40K,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,0,30,0,2,4,4,$40K - $60K,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,0,43,1,2,4,2,Less than $40K,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [33]:
test_df['income'] = test_df['income'].apply(income_match)
test_df

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,1,45,0,3,2,2,3,Blue,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,1,49,1,5,4,1,1,Blue,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,1,51,0,3,4,2,4,Blue,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,1,40,1,4,2,4,1,Blue,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,1,40,0,3,1,2,3,Blue,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,1,50,0,2,4,1,2,Blue,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,0,41,0,2,7,3,2,Blue,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,0,44,1,1,2,2,1,Blue,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,0,30,0,2,4,4,2,Blue,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,0,43,1,2,4,2,1,Silver,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189

In [34]:
test_df['card_type'] = test_df['card_type'].apply(card_type_match)
test_df

,churn,age,gender,dependents,education,marital,income,card_type,relationship_months,product_count,inactive_months,contact_count,credit_limit,revolving_balance,available_credit,amount_change,transaction_amount,transaction_count,count_change,utilization_ratio
0,1,45,0,3,2,2,3,1,39,5,1,3,12691.0,777,11914.0,1.335,1144,42,1.625,0.061
1,1,49,1,5,4,1,1,1,44,6,1,2,8256.0,864,7392.0,1.541,1291,33,3.714,0.105
2,1,51,0,3,4,2,4,1,36,4,1,0,3418.0,0,3418.0,2.594,1887,20,2.333,0.000
3,1,40,1,4,2,4,1,1,34,3,4,1,3313.0,2517,796.0,1.405,1171,20,2.333,0.760
4,1,40,0,3,1,2,3,1,21,5,1,0,4716.0,0,4716.0,2.175,816,28,2.500,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,1,50,0,2,4,1,2,1,40,3,2,3,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462
10123,0,41,0,2,7,3,2,1,25,4,2,3,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511
10124,0,44,1,1,2,2,1,1,36,5,3,4,5409.0,0,5409.0,0.819,10291,60,0.818,0.000
10125,0,30,0,2,4,4,2,1,36,4,3,3,5281.0,0,5281.0,0.535,8395,62,0.722,0.000
10126,0,43,1,2,4,2,1,2,25,6,2,4,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189